#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleSheet.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="workhouse")]
	public partial class dbWorkHouseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    #endregion
		
		public dbWorkHouseDataContext() : 
				base(global::GoogleSheet.Properties.Settings.Default.workhouseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorkHouseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorkHouseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorkHouseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorkHouseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<v_sanpham> v_sanphams
		{
			get
			{
				return this.GetTable<v_sanpham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _SanPhamId;
		
		private string _SanPhamThamChieu;
		
		private string _MaCcdc;
		
		private string _TenSanPham;
		
		private string _HienThi;
		
		private string _PartNo;
		
		private string _NhomSanPham;
		
		private string _QuyCach;
		
		private string _ViTri;
		
		private string _HinhAnh;
		
		private string _DiaChi;
		
		private string _ThongTin;
		
		private string _HanSuDung;
		
		private string _Dvt;
		
		private System.Nullable<int> _SlNhap;
		
		private System.Nullable<int> _SlXuat;
		
		private System.Nullable<int> _SlTon;
		
		private System.Nullable<decimal> _GiaTriTon;
		
		private string _TrangThai;
		
		private string _GhiChu;
		
		private string _NgayTao;
		
		private string _NguoiTao;
		
		private string _LastUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSanPhamIdChanging(string value);
    partial void OnSanPhamIdChanged();
    partial void OnSanPhamThamChieuChanging(string value);
    partial void OnSanPhamThamChieuChanged();
    partial void OnMaCcdcChanging(string value);
    partial void OnMaCcdcChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnHienThiChanging(string value);
    partial void OnHienThiChanged();
    partial void OnPartNoChanging(string value);
    partial void OnPartNoChanged();
    partial void OnNhomSanPhamChanging(string value);
    partial void OnNhomSanPhamChanged();
    partial void OnQuyCachChanging(string value);
    partial void OnQuyCachChanged();
    partial void OnViTriChanging(string value);
    partial void OnViTriChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    partial void OnHanSuDungChanging(string value);
    partial void OnHanSuDungChanged();
    partial void OnDvtChanging(string value);
    partial void OnDvtChanged();
    partial void OnSlNhapChanging(System.Nullable<int> value);
    partial void OnSlNhapChanged();
    partial void OnSlXuatChanging(System.Nullable<int> value);
    partial void OnSlXuatChanged();
    partial void OnSlTonChanging(System.Nullable<int> value);
    partial void OnSlTonChanged();
    partial void OnGiaTriTonChanging(System.Nullable<decimal> value);
    partial void OnGiaTriTonChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNgayTaoChanging(string value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnLastUpdateChanging(string value);
    partial void OnLastUpdateChanged();
    #endregion
		
		public SanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPhamId", DbType="NVarChar(255)")]
		public string SanPhamId
		{
			get
			{
				return this._SanPhamId;
			}
			set
			{
				if ((this._SanPhamId != value))
				{
					this.OnSanPhamIdChanging(value);
					this.SendPropertyChanging();
					this._SanPhamId = value;
					this.SendPropertyChanged("SanPhamId");
					this.OnSanPhamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPhamThamChieu", DbType="NVarChar(255)")]
		public string SanPhamThamChieu
		{
			get
			{
				return this._SanPhamThamChieu;
			}
			set
			{
				if ((this._SanPhamThamChieu != value))
				{
					this.OnSanPhamThamChieuChanging(value);
					this.SendPropertyChanging();
					this._SanPhamThamChieu = value;
					this.SendPropertyChanged("SanPhamThamChieu");
					this.OnSanPhamThamChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCcdc", DbType="NVarChar(255)")]
		public string MaCcdc
		{
			get
			{
				return this._MaCcdc;
			}
			set
			{
				if ((this._MaCcdc != value))
				{
					this.OnMaCcdcChanging(value);
					this.SendPropertyChanging();
					this._MaCcdc = value;
					this.SendPropertyChanged("MaCcdc");
					this.OnMaCcdcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(255)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HienThi", DbType="NVarChar(255)")]
		public string HienThi
		{
			get
			{
				return this._HienThi;
			}
			set
			{
				if ((this._HienThi != value))
				{
					this.OnHienThiChanging(value);
					this.SendPropertyChanging();
					this._HienThi = value;
					this.SendPropertyChanged("HienThi");
					this.OnHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartNo", DbType="NVarChar(255)")]
		public string PartNo
		{
			get
			{
				return this._PartNo;
			}
			set
			{
				if ((this._PartNo != value))
				{
					this.OnPartNoChanging(value);
					this.SendPropertyChanging();
					this._PartNo = value;
					this.SendPropertyChanged("PartNo");
					this.OnPartNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomSanPham", DbType="NVarChar(255)")]
		public string NhomSanPham
		{
			get
			{
				return this._NhomSanPham;
			}
			set
			{
				if ((this._NhomSanPham != value))
				{
					this.OnNhomSanPhamChanging(value);
					this.SendPropertyChanging();
					this._NhomSanPham = value;
					this.SendPropertyChanged("NhomSanPham");
					this.OnNhomSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyCach", DbType="NVarChar(255)")]
		public string QuyCach
		{
			get
			{
				return this._QuyCach;
			}
			set
			{
				if ((this._QuyCach != value))
				{
					this.OnQuyCachChanging(value);
					this.SendPropertyChanging();
					this._QuyCach = value;
					this.SendPropertyChanged("QuyCach");
					this.OnQuyCachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="NVarChar(255)")]
		public string ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(255)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(MAX)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanSuDung", DbType="NVarChar(255)")]
		public string HanSuDung
		{
			get
			{
				return this._HanSuDung;
			}
			set
			{
				if ((this._HanSuDung != value))
				{
					this.OnHanSuDungChanging(value);
					this.SendPropertyChanging();
					this._HanSuDung = value;
					this.SendPropertyChanged("HanSuDung");
					this.OnHanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dvt", DbType="NVarChar(50)")]
		public string Dvt
		{
			get
			{
				return this._Dvt;
			}
			set
			{
				if ((this._Dvt != value))
				{
					this.OnDvtChanging(value);
					this.SendPropertyChanging();
					this._Dvt = value;
					this.SendPropertyChanged("Dvt");
					this.OnDvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlNhap", DbType="Int")]
		public System.Nullable<int> SlNhap
		{
			get
			{
				return this._SlNhap;
			}
			set
			{
				if ((this._SlNhap != value))
				{
					this.OnSlNhapChanging(value);
					this.SendPropertyChanging();
					this._SlNhap = value;
					this.SendPropertyChanged("SlNhap");
					this.OnSlNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlXuat", DbType="Int")]
		public System.Nullable<int> SlXuat
		{
			get
			{
				return this._SlXuat;
			}
			set
			{
				if ((this._SlXuat != value))
				{
					this.OnSlXuatChanging(value);
					this.SendPropertyChanging();
					this._SlXuat = value;
					this.SendPropertyChanged("SlXuat");
					this.OnSlXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlTon", DbType="Int")]
		public System.Nullable<int> SlTon
		{
			get
			{
				return this._SlTon;
			}
			set
			{
				if ((this._SlTon != value))
				{
					this.OnSlTonChanging(value);
					this.SendPropertyChanging();
					this._SlTon = value;
					this.SendPropertyChanged("SlTon");
					this.OnSlTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriTon", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GiaTriTon
		{
			get
			{
				return this._GiaTriTon;
			}
			set
			{
				if ((this._GiaTriTon != value))
				{
					this.OnGiaTriTonChanging(value);
					this.SendPropertyChanging();
					this._GiaTriTon = value;
					this.SendPropertyChanged("GiaTriTon");
					this.OnGiaTriTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="NVarChar(255)")]
		public string NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(255)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="NVarChar(255)")]
		public string LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_sanpham")]
	public partial class v_sanpham
	{
		
		private string _MaCcdc;
		
		private string _TenSanPham;
		
		private string _ThongTin;
		
		private string _HinhAnh;
		
		private string _NhomSanPham;
		
		private string _ViTri;
		
		private System.Nullable<int> _SLNhap;
		
		private System.Nullable<int> _SLXuat;
		
		private System.Nullable<int> _SlTon;
		
		private string _LastUpdate;
		
		public v_sanpham()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCcdc", DbType="NVarChar(255)")]
		public string MaCcdc
		{
			get
			{
				return this._MaCcdc;
			}
			set
			{
				if ((this._MaCcdc != value))
				{
					this._MaCcdc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(255)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this._TenSanPham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(MAX)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this._ThongTin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(255)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomSanPham", DbType="NVarChar(255)")]
		public string NhomSanPham
		{
			get
			{
				return this._NhomSanPham;
			}
			set
			{
				if ((this._NhomSanPham != value))
				{
					this._NhomSanPham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="NVarChar(255)")]
		public string ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this._ViTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLNhap", DbType="Int")]
		public System.Nullable<int> SLNhap
		{
			get
			{
				return this._SLNhap;
			}
			set
			{
				if ((this._SLNhap != value))
				{
					this._SLNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLXuat", DbType="Int")]
		public System.Nullable<int> SLXuat
		{
			get
			{
				return this._SLXuat;
			}
			set
			{
				if ((this._SLXuat != value))
				{
					this._SLXuat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlTon", DbType="Int")]
		public System.Nullable<int> SlTon
		{
			get
			{
				return this._SlTon;
			}
			set
			{
				if ((this._SlTon != value))
				{
					this._SlTon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="NVarChar(255)")]
		public string LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
